version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:80
    networks:
      - api-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8080:8080
    networks:
      - api-network
      - server-network
    environment:
      - DB_URL=jdbc:postgresql://db:5432/restaurant
      - DB_USER=admin
      - DB_PASSWORD=admin
      - FRONT_HOST=http://localhost:3000,http://frontend:3000,http://127.0.0.1:3000
    depends_on:
      - db
    
  db:
    image: postgres:15-alpine
    container_name: db
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - server-network

networks:
  api-network:
    driver: bridge
    name: fron-back-network
  server-network:
    driver: bridge
    name: back-db-network